const Patient = require('./models/Patient');

const createPatients = async () => {
    const newPatient = new Patient(
        [
            {
                "name": "John Doe",
                "gender": "Male",
                "dob": "1985-06-15",
                "age": 22,
                "email": "johndoe@example.com",
                "contact": 1234567890,
                "marital_status": "Married",
                "address": "123 Maple Street, Springfield",
                "nationality": "American",
                "ID_number": "ID12345",
                "Next_of_kin": "Jane Doe",
                "Next_of_kin_phone_number": 9876543210,
                "blood_group": "O+",
                "Emergency_contact": "jane.doe@example.com",
                "relevant_medical_history": "Diabetes",
                "allergies": ["Penicillin", "Pollen"],
                "medications": ["Metformin", "Insulin"]
            },
            {
                "name": "Mary Smith",
                "gender": "Female",
                "dob": "1992-11-22",
                "age": 34,
                "email": "marysmith@example.com",
                "contact": 2345678901,
                "marital_status": "Single",
                "address": "456 Oak Lane, Seattle",
                "nationality": "Canadian",
                "ID_number": "ID67890",
                "Next_of_kin": "John Smith",
                "Next_of_kin_phone_number": 8765432109,
                "blood_group": "A-",
                "Emergency_contact": "john.smith@example.com",
                "relevant_medical_history": "Asthma",
                "allergies": ["Dust", "Cats"],
                "medications": ["Albuterol", "Steroid Inhaler"]
            },
            {
                "name": "Carlos Alvarez",
                "gender": "Male",
                "dob": "1978-03-30",
                "age": 55,
                "email": "carlosalvarez@example.com",
                "contact": 3456789012,
                "marital_status": "Divorced",
                "address": "789 Pine Road, Miami",
                "nationality": "Mexican",
                "ID_number": "ID54321",
                "Next_of_kin": "Maria Alvarez",
                "Next_of_kin_phone_number": 7654321098,
                "blood_group": "B+",
                "Emergency_contact": "maria.alvarez@example.com",
                "relevant_medical_history": "Hypertension",
                "allergies": ["Peanuts"],
                "medications": ["Lisinopril", "Atenolol"]
            },
            {
                "name": "Fatima Hassan",
                "gender": "Female",
                "dob": "1988-08-12",
                "age": 28,
                "email": "fatimahassan@example.com",
                "contact": 4567890123,
                "marital_status": "Married",
                "address": "101 Cedar Drive, Dubai",
                "nationality": "Emirati",
                "ID_number": "ID98765",
                "Next_of_kin": "Omar Hassan",
                "Next_of_kin_phone_number": 6543210987,
                "blood_group": "AB+",
                "Emergency_contact": "omar.hassan@example.com",
                "relevant_medical_history": "None",
                "allergies": ["None"],
                "medications": ["None"]
            },
            {
                "name": "Zhang Wei",
                "gender": "Male",
                "dob": "1990-12-25",
                "age": 76,
                "email": "zhangwei@example.com",
                "contact": 5678901234,
                "marital_status": "Single",
                "address": "202 Bamboo Street, Beijing",
                "nationality": "Chinese",
                "ID_number": "ID24680",
                "Next_of_kin": "Liu Wei",
                "Next_of_kin_phone_number": 5432109876,
                "blood_group": "O-",
                "Emergency_contact": "liu.wei@example.com",
                "relevant_medical_history": "None",
                "allergies": ["Shellfish"],
                "medications": ["None"]
            },
            {
                "name": "Olivia Johnson",
                "gender": "Female",
                "dob": "1995-02-18",
                "age": 34,
                "email": "oliviajohnson@example.com",
                "contact": 6789012345,
                "marital_status": "Single",
                "address": "303 Elm Street, Boston",
                "nationality": "British",
                "ID_number": "ID13579",
                "Next_of_kin": "Emily Johnson",
                "Next_of_kin_phone_number": 6543210987,
                "blood_group": "A+",
                "Emergency_contact": "emily.johnson@example.com",
                "relevant_medical_history": "Allergies",
                "allergies": ["Peanuts", "Dust"],
                "medications": ["EpiPen"]
            },
            {
                "name": "Emma Brown",
                "gender": "Female",
                "dob": "1987-09-07",
                "age": 5,
                "email": "emmabrown@example.com",
                "contact": 7890123456,
                "marital_status": "Married",
                "address": "707 Ash Street, London",
                "nationality": "British",
                "ID_number": "ID97531",
                "Next_of_kin": "Michael Brown",
                "Next_of_kin_phone_number": 5432109876,
                "blood_group": "B-",
                "Emergency_contact": "michael.brown@example.com",
                "relevant_medical_history": "Hypertension",
                "allergies": ["Dust"],
                "medications": ["Lisinopril"]
            },
            {
                "name": "Amir Ali",
                "gender": "Male",
                "dob": "1991-04-20",
                "age": 20,
                "email": "amirali@example.com",
                "contact": 8901234567,
                "marital_status": "Single",
                "address": "808 Cherry Lane, Lahore",
                "nationality": "Pakistani",
                "ID_number": "ID75324",
                "Next_of_kin": "Sara Ali",
                "Next_of_kin_phone_number": 4321098765,
                "blood_group": "O+",
                "Emergency_contact": "sara.ali@example.com",
                "relevant_medical_history": "None",
                "allergies": ["None"],
                "medications": ["None"]
            },
            {
                "name": "Nina Patel",
                "gender": "Female",
                "dob": "1993-06-12",
                "age": 30,
                "email": "ninapatel@example.com",
                "contact": 9012345678,
                "marital_status": "Single",
                "address": "909 Maple Street, Mumbai",
                "nationality": "Indian",
                "ID_number": "ID24689",
                "Next_of_kin": "Raj Patel",
                "Next_of_kin_phone_number": 3210987654,
                "blood_group": "AB-",
                "Emergency_contact": "raj.patel@example.com",
                "relevant_medical_history": "Asthma",
                "allergies": ["Pollen"],
                "medications": ["Inhaler"]
            },
            {
                "name": "Alex Kim",
                "gender": "Male",
                "dob": "1998-08-19",
                "age": 80,
                "email": "alexkim@example.com",
                "contact": 2345678901,
                "marital_status": "Single",
                "address": "404 Pine Street, Seoul",
                "nationality": "South Korean",
                "ID_number": "ID67892",
                "Next_of_kin": "Jin Kim",
                "Next_of_kin_phone_number": 2109876543,
                "blood_group": "B+",
                "Emergency_contact": "jin.kim@example.com",
                "relevant_medical_history": "None",
                "allergies": ["None"],
                "medications": ["None"]
            },
            {
                "name": "Sophia White",
                "gender": "Female",
                "dob": "1989-03-05",
                "age": 65,
                "email": "sophiawhite@example.com",
                "contact": 3456789012,
                "marital_status": "Married",
                "address": "505 Birch Avenue, Sydney",
                "nationality": "Australian",
                "ID_number": "ID45367",
                "Next_of_kin": "Liam White",
                "Next_of_kin_phone_number": 1098765432,
                "blood_group": "O+",
                "Emergency_contact": "liam.white@example.com",
                "relevant_medical_history": "None",
                "allergies": ["None"],
                "medications": ["None"]
            },
            {
                "name": "Isabella Martinez",
                "gender": "Female",
                "dob": "1990-07-16",
                "age": 40,
                "email": "isabellamartinez@example.com",
                "contact": 4567890123,
                "marital_status": "Married",
                "address": "606 Cedar Street, Madrid",
                "nationality": "Spanish",
                "ID_number": "ID97431",
                "Next_of_kin": "Carlos Martinez",
                "Next_of_kin_phone_number": 1987654321,
                "blood_group": "A+",
                "Emergency_contact": "carlos.martinez@example.com",
                "relevant_medical_history": "Diabetes",
                "allergies": ["None"],
                "medications": ["Insulin"]
            },
            {
                "name": "Henry Lewis",
                "gender": "Male",
                "dob": "1984-01-10",
                "age": 18,
                "email": "henrylewis@example.com",
                "contact": 5678901234,
                "marital_status": "Divorced",
                "address": "707 Walnut Street, Los Angeles",
                "nationality": "American",
                "ID_number": "ID76543",
                "Next_of_kin": "Sarah Lewis",
                "Next_of_kin_phone_number": 2345678901,
                "blood_group": "B-",
                "Emergency_contact": "sarah.lewis@example.com",
                "relevant_medical_history": "None",
                "allergies": ["Peanuts"],
                "medications": ["None"]
            },
            {
                "name": "Liam Carter",
                "gender": "Male",
                "dob": "1982-12-12",
                "age": 12,
                "email": "liamcarter@example.com",
                "contact": 6789012345,
                "marital_status": "Married",
                "address": "808 Oak Street, Toronto",
                "nationality": "Canadian",
                "ID_number": "ID65789",
                "Next_of_kin": "Emily Carter",
                "Next_of_kin_phone_number": 1098765432,
                "blood_group": "O+",
                "Emergency_contact": "emily.carter@example.com",
                "relevant_medical_history": "High Cholesterol",
                "allergies": ["None"],
                "medications": ["Atorvastatin"]
            },
            {
                "name": "Ava Davis",
                "gender": "Female",
                "dob": "1997-04-24",
                "age": 90,
                "email": "avadavis@example.com",
                "contact": 7890123456,
                "marital_status": "Single",
                "address": "909 Maple Avenue, Chicago",
                "nationality": "American",
                "ID_number": "ID98435",
                "Next_of_kin": "Olivia Davis",
                "Next_of_kin_phone_number": 8765432109,
                "blood_group": "AB+",
                "Emergency_contact": "olivia.davis@example.com",
                "relevant_medical_history": "None",
                "allergies": ["None"],
                "medications": ["None"]
            },
            {
                "name": "Elijah Anderson",
                "gender": "Male",
                "dob": "1989-05-15",
                "age": 43,
                "email": "elijaha@example.com",
                "contact": 8901234567,
                "marital_status": "Single",
                "address": "1212 Pine Street, Vancouver",
                "nationality": "Canadian",
                "ID_number": "ID34512",
                "Next_of_kin": "Mia Anderson",
                "Next_of_kin_phone_number": 6543210987,
                "blood_group": "O-",
                "Emergency_contact": "mia.anderson@example.com",
                "relevant_medical_history": "None",
                "allergies": ["None"],
                "medications": ["None"]
            }
        ])
    newPatient.save();
}

module.exports = createPatients;